import {
  secondaryGrey,
  primaryGrey,
  bgDefaultColor,
  defaultGreen,
  defaultOrange,
  bgAccentColor,
  placeholderColor,
  borderColor,
  forgotPasswordColor,
  borderFormColor,
  drawerBgColor,
} from "./colors";

import {
  PoppinsBold,
  PoppinsItalicBold,
  PoppinsItalicLight,
  PoppinsItalicRegular,
  PoppinsLight,
  PoppinsRegular,
  RobotoBold,
  RobotoItalicBold,
  RobotoItalicLight,
  RobotoItalicRegular,
  RobotoLight,
  RobotoRegular,
} from "./fonts";

export {
  secondaryGrey,
  primaryGrey,
  bgDefaultColor,
  defaultOrange,
  defaultGreen,
  bgAccentColor,
  PoppinsBold,
  PoppinsItalicBold,
  PoppinsItalicLight,
  PoppinsItalicRegular,
  PoppinsLight,
  PoppinsRegular,
  RobotoBold,
  RobotoItalicBold,
  RobotoItalicLight,
  RobotoItalicRegular,
  RobotoLight,
  RobotoRegular,
  placeholderColor,
  borderColor,
  borderFormColor,
  forgotPasswordColor,
  drawerBgColor,
};
